department = Department.create!(name: "Denver Department", floor: "Basement")
department_2 = Department.create!(name: "Mexico Department", floor: "Basement")
department_3 = Department.create!(name: "Texas Department", floor: "Top Floor")
employee = department.employees.create!(name: "Wes", level: 2)
employee = department_2.employees.create!(name: "Ashley", level: 3)
employee = department_2.employees.create!(name: "Dave", level: 4)
